[package]
name = "moomer"
version = "0.1.0"
edition = "2021"

[dependencies]
screenshots = "0.8"
winit = "0.28"
pixels = "0.13"
image = "0.24"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2"

